### ISSUE TITLE
Cursor management: define default cursor and interaction default cursor for the complete game. Maintain interaction cursor customization in tooltip asset. If there is customization use it, otherwise use default cursors defined for the complete game.

### ISSUE THREAD

**Issue by fjortegan** [IES-Rafael-Alberti/game-off-2022#173]

**Comment by Kenflin** [comment]
The branch im using: [168-fix-tooltip-and-cursor](https://github.com/IES-Rafael-Alberti/game-off-2022/tree/168-fix-tooltip-and-cursor)

**Comment by Kenflin** [comment]
Cursor Done - https://github.com/IES-Rafael-Alberti/game-off-2022/commit/79100c1c58f5e3fa337f29997bca551456ffcfd0
